version: '3.7'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    container_name: reverse-proxy
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
      - "--ping=true"
      - "--accesslog=true"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro

  dynamic-server:
    # Notre container pour les accès dynamique
    build: ./dynamic-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dynamic-server.rule=Path(`/persons/`)"
      - "traefik.http.routers.dynamic-server.priority=2"

  static-server:
    build: ./static-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static-server.rule=PathPrefix(`/`)"
      - "traefik.http.routers.static-server.priority=1"

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
